import { Dimensions, StyleSheet, Platform } from 'react-native';

const { width, height } = Dimensions.get("window");

// Responsive scaling functions for cross-platform consistency
const scale = (size) => (width / 375) * size;
const verticalScale = (size) => (height / 812) * size;
const moderateScale = (size, factor = 0.5) => size + (scale(size) - size) * factor;

// Platform-specific status bar height
const STATUSBAR_HEIGHT = Platform.select({
    ios: 44,
    android: 24,
    default: 0,
});

const home_styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000000',
        position: 'relative',
    },
    navbar: {
        backgroundColor: '#00bcd4',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(20),
        paddingVertical: verticalScale(12),
        borderBottomWidth: 2,
        paddingTop: STATUSBAR_HEIGHT + verticalScale(12),
        borderBottomColor: '#ffffff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        minHeight: STATUSBAR_HEIGHT + verticalScale(56),
    },
    settingsButton: {
        padding: scale(8),
        borderRadius: 8,
        backgroundColor: 'rgba(0, 0, 0, 0.1)',
    },
    title: {
        color: '#000000',
        fontSize: moderateScale(22),
        fontWeight: 'bold',
        textAlign: 'center',
        flex: 1,
        letterSpacing: 1,
    },
    userInfo: {
        alignItems: 'flex-end',
    },
    userName: {
        color: '#000000',
        fontSize: moderateScale(13),
        fontWeight: '600',
    },
    dropdown: {
        position: 'absolute',
        top: STATUSBAR_HEIGHT + verticalScale(60),
        left: scale(10),
        backgroundColor: '#ffffff',
        borderRadius: 12,
        padding: scale(6),
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4.65,
        elevation: 99,
        zIndex: 9999,
        minWidth: scale(140),
    },
    dropdownItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: verticalScale(12),
        paddingHorizontal: scale(14),
        borderRadius: 8,
        marginVertical: 2,
    },
    dropdownText: {
        color: '#000000',
        fontSize: moderateScale(14),
        fontWeight: '500',
    },
    content: {
        flex: 1,
        padding: scale(16),
    },
    listContainer: {
        paddingBottom: verticalScale(20),
        paddingTop: verticalScale(10),
    },
    card: {
        backgroundColor: 'rgba(0, 188, 212, 0.08)',
        borderWidth: 2,
        borderColor: '#00bcd4',
        borderRadius: 16,
        padding: scale(16),
        marginBottom: verticalScale(12),
        shadowColor: '#00bcd4',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 3.84,
        elevation: 5,
    },
    approvedCard: {
        opacity: 0.75,
        borderColor: '#00FF00',
        backgroundColor: 'rgba(0, 255, 0, 0.05)',
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: verticalScale(12),
        flexWrap: 'wrap',
        gap: scale(8),
    },
    cardTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    cardImageIndicator: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: 'rgba(0, 188, 212, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: scale(8),
    },
    cardTitle: {
        color: '#00bcd4',
        fontSize: moderateScale(16),
        fontWeight: 'bold',
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(4),
        borderRadius: 20,
        borderWidth: 1,
    },
    statusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginRight: scale(6),
    },
    statusBadgeText: {
        fontSize: moderateScale(11),
        fontWeight: '600',
        textTransform: 'uppercase',
    },
    cardBody: {
        marginBottom: verticalScale(8),
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: verticalScale(6),
    },
    cardText: {
        color: '#ffffff',
        fontSize: moderateScale(14),
        marginLeft: scale(8),
        lineHeight: 20,
        flex: 1,
    },
    cardStatus: {
        alignSelf: 'flex-start',
        backgroundColor: 'rgba(0, 188, 212, 0.2)',
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(6),
        borderRadius: 8,
        borderWidth: 1,
        marginVertical: verticalScale(10),
    },
    statusText: {
        fontSize: moderateScale(11),
        fontWeight: '600',
        textTransform: 'uppercase',
    },
    reviewButton: {
        backgroundColor: '#00bcd4',
        paddingVertical: verticalScale(12),
        paddingHorizontal: scale(20),
        borderRadius: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: verticalScale(8),
        shadowColor: '#00bcd4',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    reviewButtonText: {
        color: '#000000',
        fontSize: moderateScale(14),
        fontWeight: 'bold',
        marginRight: scale(6),
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    emptyCard: {
        backgroundColor: 'rgba(0, 188, 212, 0.1)',
        borderWidth: 2,
        borderColor: '#00bcd4',
        borderRadius: 16,
        padding: scale(35),
        marginHorizontal: scale(20),
        alignItems: 'center',
    },
    emptyTitle: {
        color: '#00bcd4',
        fontSize: moderateScale(22),
        fontWeight: 'bold',
        marginBottom: verticalScale(12),
        textAlign: 'center',
    },
    emptyText: {
        color: '#ffffff',
        fontSize: moderateScale(14),
        textAlign: 'center',
        lineHeight: 22,
        opacity: 0.8,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        backgroundColor: '#1a1a1a',
        borderRadius: 20,
        padding: scale(22),
        margin: scale(20),
        width: width * 0.9,
        maxWidth: 400,
        borderWidth: 2,
        borderColor: '#00bcd4',
        shadowColor: '#00bcd4',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 10,
    },
    closeButton: {
        position: 'absolute',
        top: scale(10),
        right: scale(10),
        width: scale(44),
        height: scale(44),
        borderRadius: scale(22),
        backgroundColor: 'rgba(0, 188, 212, 0.15)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10,
    },
    modalTitle: {
        color: '#00bcd4',
        fontSize: moderateScale(20),
        fontWeight: 'bold',
        textAlign: 'center',
        marginTop: verticalScale(8),
        marginBottom: verticalScale(20),
    },
    modalContent: {
        marginBottom: verticalScale(20),
    },
    modalRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: verticalScale(14),
        paddingRight: scale(10),
    },
    modalIconContainer: {
        width: scale(36),
        height: scale(36),
        borderRadius: scale(18),
        backgroundColor: 'rgba(0, 188, 212, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: scale(12),
    },
    modalTextContainer: {
        flex: 1,
    },
    modalLabel: {
        color: '#00bcd4',
        fontSize: moderateScale(11),
        fontWeight: '600',
        textTransform: 'uppercase',
        marginBottom: verticalScale(2),
        letterSpacing: 0.5,
    },
    modalValue: {
        color: '#ffffff',
        fontSize: moderateScale(15),
        lineHeight: 22,
    },
    modalText: {
        color: '#ffffff',
        fontSize: moderateScale(15),
        marginBottom: verticalScale(10),
        lineHeight: 22,
    },
    actionContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: scale(12),
    },
    declineButton: {
        backgroundColor: '#ff4444',
        paddingVertical: verticalScale(14),
        paddingHorizontal: scale(20),
        borderRadius: 12,
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#ff4444',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    declineButtonText: {
        color: '#ffffff',
        fontSize: moderateScale(15),
        fontWeight: 'bold',
        marginLeft: scale(6),
    },
    acceptButton: {
        backgroundColor: '#00ff00',
        paddingVertical: verticalScale(14),
        paddingHorizontal: scale(20),
        borderRadius: 12,
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#00ff00',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    acceptButtonText: {
        color: '#000000',
        fontSize: moderateScale(15),
        fontWeight: 'bold',
        marginLeft: scale(6),
    },
    actionText: {
        color: '#000000',
        fontSize: moderateScale(15),
        fontWeight: 'bold',
    },
    // Toast styles
    toastOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    toastContainer: {
        backgroundColor: '#1a1a1a',
        borderRadius: 16,
        paddingVertical: verticalScale(24),
        paddingHorizontal: scale(32),
        borderWidth: 2,
        borderColor: '#00bcd4',
        alignItems: 'center',
        shadowColor: '#00bcd4',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 10,
        minWidth: scale(200),
        maxWidth: width * 0.8,
    },
    toastText: {
        color: '#ffffff',
        fontSize: moderateScale(16),
        fontWeight: '600',
        textAlign: 'center',
    },
    // Visitor image styles
    visitorImageContainer: {
        alignItems: 'center',
        marginBottom: verticalScale(16),
    },
    visitorImage: {
        width: scale(100),
        height: scale(100),
        borderRadius: scale(50),
        borderWidth: 3,
        borderColor: '#00bcd4',
    },
    noImageContainer: {
        alignItems: 'center',
        marginBottom: verticalScale(16),
        paddingVertical: verticalScale(10),
    },
    noImageText: {
        color: '#666',
        fontSize: moderateScale(12),
        marginTop: verticalScale(8),
        fontStyle: 'italic',
    },
    // New appointment toast styles
    newAppointmentToast: {
        position: 'absolute',
        top: STATUSBAR_HEIGHT + verticalScale(70),
        left: scale(20),
        right: scale(20),
        backgroundColor: '#1a1a1a',
        borderRadius: 12,
        paddingVertical: verticalScale(14),
        paddingHorizontal: scale(16),
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#00bcd4',
        shadowColor: '#00bcd4',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 20,
        zIndex: 9998,
    },
    newAppointmentToastText: {
        marginLeft: scale(12),
        flex: 1,
    },
    newAppointmentTitle: {
        color: '#00bcd4',
        fontSize: moderateScale(14),
        fontWeight: 'bold',
    },
    newAppointmentSubtitle: {
        color: '#ffffff',
        fontSize: moderateScale(12),
        marginTop: verticalScale(2),
    },
    // FIX 8: Delete Modal styles
    deleteModalContainer: {
        backgroundColor: '#1a1a1a',
        borderRadius: 16,
        padding: scale(20),
        margin: scale(30),
        width: width * 0.85,
        maxWidth: 320,
        borderWidth: 2,
        borderColor: '#FF6B6B',
        shadowColor: '#FF6B6B',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 10,
    },
    deleteModalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: verticalScale(16),
    },
    deleteModalTitle: {
        color: '#FF6B6B',
        fontSize: moderateScale(18),
        fontWeight: 'bold',
        marginLeft: scale(10),
    },
    deleteModalText: {
        color: '#ffffff',
        fontSize: moderateScale(14),
        textAlign: 'center',
        lineHeight: 22,
        marginBottom: verticalScale(16),
        opacity: 0.9,
    },
    deleteModalInfo: {
        backgroundColor: 'rgba(255, 107, 107, 0.1)',
        borderRadius: 8,
        padding: scale(12),
        marginBottom: verticalScale(20),
        borderWidth: 1,
        borderColor: 'rgba(255, 107, 107, 0.3)',
    },
    deleteModalInfoText: {
        color: '#ffffff',
        fontSize: moderateScale(13),
        textAlign: 'center',
    },
    deleteModalActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: scale(12),
    },
    deleteModalCloseButton: {
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        paddingVertical: verticalScale(12),
        paddingHorizontal: scale(20),
        borderRadius: 10,
        flex: 1,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    deleteModalCloseText: {
        color: '#ffffff',
        fontSize: moderateScale(14),
        fontWeight: '600',
    },
    deleteModalDeleteButton: {
        backgroundColor: '#FF6B6B',
        paddingVertical: verticalScale(12),
        paddingHorizontal: scale(20),
        borderRadius: 10,
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#FF6B6B',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    deleteModalDeleteText: {
        color: '#ffffff',
        fontSize: moderateScale(14),
        fontWeight: 'bold',
        marginLeft: scale(6),
    },
});

export default home_styles;