"""add wait_until to visit_sessions

Revision ID: 15ac25e77d3c
Revises: 624f24b7ff64
Create Date: 2026-08-03 12:54:21.170484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ac25e77d3c'
down_revision: Union[str, Sequence[str], None] = '624f24b7ff64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wait_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_sessions', schema=None) as batch_op:
        batch_op.drop_column('wait_until')

    # ### end Alembic commands ###
