"""add wait_reminder_sent_at to visit_sessions

Revision ID: 3babf4808a8d
Revises: 15ac25e77d3c
Create Date: 2026-08-17 14:14:13.464870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3babf4808a8d'
down_revision: Union[str, Sequence[str], None] = '15ac25e77d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wait_reminder_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_sessions', schema=None) as batch_op:
        batch_op.drop_column('wait_reminder_sent_at')

    # ### end Alembic commands ###
