"""add available_again_at to visit_sessions

Revision ID: 624f24b7ff64
Revises: d873d0d18d9b
Create Date: 2026-08-03 08:07:50.341685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '624f24b7ff64'
down_revision: Union[str, Sequence[str], None] = 'd873d0d18d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_employees_employee_code'), ['employee_code'])
        batch_op.create_unique_constraint(batch_op.f('uq_employees_invite_token'), ['invite_token'])

    with op.batch_alter_table('visit_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_again_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_sessions', schema=None) as batch_op:
        batch_op.drop_column('available_again_at')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_employees_invite_token'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_employees_employee_code'), type_='unique')

    # ### end Alembic commands ###
