"""add wait_minutes to visit_sessions

Revision ID: 910b83a88b8a
Revises: 3babf4808a8d
Create Date: 2026-08-17 14:34:43.391619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '910b83a88b8a'
down_revision: Union[str, Sequence[str], None] = '3babf4808a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wait_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_sessions', schema=None) as batch_op:
        batch_op.drop_column('wait_minutes')

    # ### end Alembic commands ###
