"""add host-alert fields to visit_sessions

Revision ID: d873d0d18d9b
Revises: c7d611282b50
Create Date: 2026-07-30 13:36:26.851548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd873d0d18d9b'
down_revision: Union[str, Sequence[str], None] = 'c7d611282b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host_alert_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('host_response', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('visitor_choice', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('message_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status_token', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_visit_sessions_status_token', ['status_token'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('status_token')
        batch_op.drop_column('message_text')
        batch_op.drop_column('visitor_choice')
        batch_op.drop_column('host_response')
        batch_op.drop_column('host_alert_sent_at')

    # ### end Alembic commands ###
